DROP TABLE IF EXISTS "Reservation" CASCADE;
DROP TABLE IF EXISTS "ResourceBan" CASCADE;
DROP TABLE IF EXISTS "Resource" CASCADE;
DROP TABLE IF EXISTS "User" CASCADE;
DROP TABLE IF EXISTS "Organization" CASCADE;
DROP TABLE IF EXISTS "_prisma_migrations" CASCADE;
DROP TYPE IF EXISTS "ReservationStatus" CASCADE;
DROP TYPE IF EXISTS "Role" CASCADE;
